### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by bsr203** [soonlive/nova#1]
Hi @soonlive 

I am exploring graphql/relay and found your app makes good use of it. Can you please let me know how to run it. 

i could run the api server with

`npm run start`

it starts a `graphql` server at `http://localhost:4000/grahql` and an express app at http://localhost:4000/

now how to start the frontend server

I ran `webpack` and it generated files in /build/public (index.html was missing so copied one there)
then tried `gulp webpack`. It started the app on port 5000 but cant access the graphql server. How do u run it?

thanks for your effort and making it available,
Cheers,
bsr

**Comment by soonlive** [comment]
Hi @bsr203 

I have commited the latest codes, so u can just run  `gulp` under `nova-webapp` and `nova-api` folders to start the servers.

there are three servers totally.

`http://127.0.0.1:3000`              client server
`http://127.0.0.1:5000/public`    webpack-dev-server
`http://127.0.0.1:4000/graphql` graphql server

u also need to run an nginx server to proxy these servers for handling different http request.

`
	location ~* \.(hot-update.json)$ {
            proxy_pass http://127.0.0.1:5000$uri$is_args$args;
	}

	location ~* \.(hot-update.js)$ {
            proxy_pass http://127.0.0.1:5000$uri$is_args$args;
	}

        location / {
            include     proxy.conf; 
            proxy_pass   http://127.0.0.1:3000;
        }

        location /api {
            include     proxy.conf; 
            proxy_pass   http://127.0.0.1:4000/api;
        }

        location /rest/api {
            include     proxy.conf; 
            proxy_pass   http://127.0.0.1:4000/rest/api;
        }

        location /wechat {
            include     proxy.conf; 
            proxy_pass   http://127.0.0.1:3000/wechat;
        }

        location /graphql {
            include     proxy.conf; 
            proxy_pass   http://127.0.0.1:4000/graphql;
        }

        location /public {
            include     proxy.conf; 
            proxy_pass   http://127.0.0.1:5000/public;
        }
`

I will complete the readme for u to show how to run when I have time.

This is the first time I reply in english, if there is any thing confusing u , please let me know :)

**Comment by bsr203** [comment]
Hi,

thanks a ton for helping me out.

couple more things. Please mention to install pm2 as it wasn't in my system and there was no warning.

```
npm install pm2 -g
```

Also, running gulp on webapp didn't give any status message, so I tried running it manually. May be gulp had swallowed the status message.

```
~/W/G/n/nova-webapp ❯❯❯ gulp                                                                                                                         master
[07:27:17] Requiring external module babel-core/register
[07:27:19] Using gulpfile ~/Work/Github/nova/nova-webapp/gulpfile.babel.js
[07:27:19] Starting 'start'...
[07:27:19] Finished 'start' after 14 ms
[07:27:19] Starting 'default'...
[07:27:19] Finished 'default' after 22 μs
~/W/G/n/nova-webapp ❯❯❯ pm2 start processes.json                                                                                                     master
[PM2] restartProcessId process id 0
[PM2] restartProcessId process id 1
┌─────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name        │ id │ mode │ pid   │ status │ restart │ uptime │ memory      │ watching │
├─────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ nova-webapp     │ 0  │ fork │ 12238 │ online │ 1       │ 0s     │ 18.734 MB   │ disabled │
│ nova-webapp-dev │ 1  │ fork │ 12259 │ online │ 1       │ 0s     │ 8.781 MB    │ disabled │
└─────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
~/W/G/n/nova-webapp ❯❯❯  

````

2. Can you please show me the content of `proxy.conf`. I never used nginx and it gives error with the config you given.

```
 sudo nginx                                                                                                                        ⏎ master
Password:
nginx: [emerg] open() "/usr/local/etc/nginx/proxy.conf" failed (2: No such file or directory) in /usr/local/etc/nginx/nginx.conf:89
/u/l/e/nginx ❯❯❯    

```

thanks again for your help.

**Comment by bsr203** [comment]
@soonlive 

I just commented 

and getting this error in crome console for `http://localhost:8080/login`

```
ollowing reasons:

1. Token doesn't exists, are you sure it hasn't expired or been revoked?
_markAsRejected @ RelayPendingQueryTracker.js:162_handleSubtractedQueryFailure @ RelayPendingQueryTracker.js:143tryCallOne @ core.js:37(anonymous function) @ core.js:103flush @ browser-raw.js:52


invariant.js:39 Uncaught Error: Invariant Violation: onlyChild must be passed a children with exactly one child.invariant @ invariant.js:39onlyChild @ onlyChild.js:29render @ StaticContainer.react.js:63ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:579ReactCompositeComponentMixin._renderValidatedComponent @ ReactCompositeComponent.js:599ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:552ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:536ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:465ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.receiveComponent @ ReactCompositeComponent.js:397ReactReconciler.receiveComponent @ ReactReconciler.js:87ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:554ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:536ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:465ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.receiveComponent @ ReactCompositeComponent.js:397ReactReconciler.receiveComponent @ ReactReconciler.js:87ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:554ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:536ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:465ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.receiveComponent @ ReactCompositeComponent.js:397ReactReconciler.receiveComponent @ ReactReconciler.js:87ReactCompositeComponentMixin._updateRenderedComponent @ ReactCompositeComponent.js:554ReactCompositeComponentMixin._performComponentUpdate @ ReactCompositeComponent.js:536ReactCompositeComponentMixin.updateComponent @ ReactCompositeComponent.js:465ReactPerf.measure.wrapper @ ReactPerf.js:66ReactCompositeComponentMixin.performUpdateIfNecessary @ ReactCompositeComponent.js:413ReactReconciler.performUpdateIfNecessary @ ReactReconciler.js:102runBatchedUpdates @ ReactUpdates.js:129Mixin.perform @ Transaction.js:136Mixin.perform @ Transaction.js:136assign.perform @ ReactUpdates.js:86flushBatchedUpdates @ ReactUpdates.js:147ReactPerf.measure.wrapper @ ReactPerf.js:66Mixin.closeAll @ Transaction.js:202Mixin.perform @ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62enqueueUpdate @ ReactUpdates.js:176enqueueUpdate @ ReactUpdateQueue.js:24ReactUpdateQueue.enqueueSetState @ ReactUpdateQueue.js:190ReactComponent.setState @ ReactComponent.js:64onReadyStateChange @ RelayRootContainer.js:148(anonymous function) @ GraphQLQueryRunner.js:163tryCallOne @ core.js:37(anonymous function) @ core.js:103flush @ browser-raw.js:52

```

Do I have to create a token manually somehow, or can the login/register page let me allow to create or login as a mock user. I tried `http://localhost:8080/register` , same error. Let me know how to proceed and if there a test user.

 thanks again.

**Comment by bsr203** [comment]
Also, not sure why the introspection query doesn't return any result

```
 curl -XPOST -H 'Content-Type:application/graphql'  -d '{__schema { queryType { name, fields { name, description} }}}' http://localhost:4000/graphql
{
  "errors": [
    {
      "message": "Must provide query string."
    }
  ]
}%  
```


```
curl -XPOST -H 'Content-Type:application/graphql'  -d '{__schema { queryType { name, fields { name, description} }}}' http://localhost:8080/graphql
{
  "errors": [
    {
      "message": "Must provide query string."
    }
  ]
}%                                     

```

**Comment by bsr203** [comment]
Also can you please comment on what all features are in this app. I see `REST` api, `wechat`, and a graphql based e-commerce model.  I was looking this repo as a learning point of graphql + relay but curious seeing all the features. thanks
